=== Piti-14/RETO-01/departamentos_jph.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Departamentos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Departamento">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Nombre" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Piti-14/RETO-01/Departamentos_XSD_jph.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Departamentos xmlns:xs="http://www.w3.org/2001/XMLSchema"
xs:noNamespaceSchemaLocation="departamentos_jph.xsd">
    <Departamento>
        <Nombre>COMERCIAL</Nombre>
    </Departamento>
    <Departamento>
        <Nombre>CONTABILIDAD</Nombre>
    </Departamento>
    <Departamento>
        <Nombre>INFORM√ÅTICA</Nombre>
    </Departamento>
    <Departamento>
        <Nombre>PERSONAL</Nombre>
    </Departamento>
</Departamentos>
