=== Piti-14/RETO-01/grupos_jph.dtd
<!ELEMENT GruposProfesionales (Grupo+)>
    <!ELEMENT Grupo (Numero, Formacion+, SalarioBase)>
        <!ELEMENT Numero (#PCDATA)>
        <!ELEMENT Formacion (#PCDATA)>
        <!ELEMENT SalarioBase (#PCDATA)>

=== Piti-14/RETO-01/GruposProfesionales_jph.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE GruposProfesionales SYSTEM "grupos_jph.dtd">
<GruposProfesionales>
    <Grupo>
        <Numero>1</Numero>
        <Formacion>Estudios Universitarios y Doctorado</Formacion>
        <SalarioBase>2500</SalarioBase>
    </Grupo>
    <Grupo>
        <Numero>2</Numero>
        <Formacion>Estudios Universitarios y MÃ¡ster</Formacion>
        <SalarioBase>2100</SalarioBase>
    </Grupo>
    <Grupo>
        <Numero>3</Numero>
        <Formacion>Estudios Universitarios o Grado Superior</Formacion>
        <SalarioBase>1700</SalarioBase>
    </Grupo>
    <Grupo>
        <Numero>4</Numero>
        <Formacion>Estudios Universitarios o de Grado</Formacion>
        <SalarioBase>1400</SalarioBase>
    </Grupo>
    <Grupo>
        <Numero>5</Numero>
        <Formacion>Estudios de Grado Medio o Superior</Formacion>
        <SalarioBase>1100</SalarioBase>
    </Grupo>
</GruposProfesionales>
